_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.7
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: wikipedia
epochs:
    value: 5
learning_rate:
    value: 5e-05
model_name:
    value: F_GRU_TFTFF2step_10000_Schedule_Reinforce_Step_MLPForget_Full_Fintune
